name: appleclang

on: pull_request

jobs:
  test_cxx:
    runs-on: macos-latest

    strategy:
      matrix:
        CXX_STD: [ 11, 14, 17, 20 ]
        BUILD_TYPE: [ Debug, Release ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }}
          -DCMAKE_CXX_STANDARD=${{ matrix.CXX_STD }}
          -DLSD_TEST=ON
          -DLSD_TEST_MATRIX=ON

      - name: Build Test
        run: cmake --build ${{ github.workspace }}/build --target all -- -j 9

      - name: Run Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ matrix.BUILD_TYPE }} --extra-verbose --output-on-failure -j9
